### ISSUE TITLE
python3.8  TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by xavierskip** [xavierskip/dns-observe#2]
```
Traceback (most recent call last):
  File "./dns-observe", line 5, in <module>
    from dns_observe.dns import main
  File "/home/y/uv/test/.venv/lib/python3.8/site-packages/dns_observe/__init__.py", line 1, in <module>
    from .dns import *
  File "/home/y/uv/test/.venv/lib/python3.8/site-packages/dns_observe/dns.py", line 67, in <module>
    class DNSQuery:
  File "/home/y/uv/test/.venv/lib/python3.8/site-packages/dns_observe/dns.py", line 159, in DNSQuery
    def _parse_name(self, response: bytes, offset: int) -> tuple[str, int]:
TypeError: 'type' object is not subscriptable
```

**Comment by xavierskip** [comment]
no plane to test in python 3.8

**Comment by xavierskip** [comment]
test under python 3.8 use https://github.com/astral-sh/uv `uv venv --python 3.8`

 you can use `from typing import Tuple`  for python 3.8 compatibility.

PEP 585 -- Type Hinting Generics In Standard Collections  https://peps.python.org/pep-0585/

**Comment by xavierskip** [comment]
7f40e157e84c85db83191cc07f02b53e2bcea704 fix it.
