### ISSUE TITLE
` python -m dns_observe gist.github.com`  OSError: packed IP wrong length for inet_ntoa

### ISSUE THREAD

**Issue by xavierskip** [xavierskip/dns-observe#4]
```
> python -m dns_observe gist.github.com
Time: 2024-11-19 21:11:53.699163, Name: gist.github.com, TTL: 236, Data: 243.185.187.39
Time: 2024-11-19 21:11:53.700164, Name: gist.github.com, TTL: 195, Data: 243.185.187.39
Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Code\python\DNS-pollution\src\dns_observe\__main__.py", line 3, in <module>
    main()
  File "C:\Code\python\DNS-pollution\src\dns_observe\dns.py", line 225, in main
    querys = dns.query(args.domain)  # 查询记录信息
  File "C:\Code\python\DNS-pollution\src\dns_observe\dns.py", line 86, in query
    print(f"Time: {now}, Name: {answer.name}, TTL: {answer.ttl}, Data: {answer.ip_address}")
  File "C:\Code\python\DNS-pollution\src\dns_observe\dns.py", line 203, in ip_address
    return  socket.inet_ntoa(self.data)
OSError: packed IP wrong length for inet_ntoa
```

**Comment by xavierskip** [comment]
https://github.com/xavierskip/dns-observe/commit/57664acada455581ee3ee1800f87ac91e222772b fix it!
